const cron = require('node-cron');
const Alert = require('../models/Alert');
const alertRepository = require('../repositories/alertRepository');
const kafkaProducer = require('../kafka/producer');

// Anchor points for Indian cities/towns that are safely inland.
// Each alert is generated by picking a random anchor and adding ±COORD_JITTER degrees
// (~17 km radius), keeping all points well within land borders.
const INDIA_LAND_POINTS = [
  // Delhi & NCR
  [28.6139, 77.2090], [28.4595, 77.0266], [28.6692, 77.4538],
  // Uttar Pradesh
  [27.1767, 78.0081], [26.4499, 80.3319], [26.8467, 80.9462],
  [25.4358, 81.8463], [25.3176, 82.9739], [28.3670, 79.4304],
  [26.1197, 85.3910],
  // Bihar
  [25.5941, 85.1376], [24.7914, 84.9994], [25.1429, 85.5349],
  // Rajasthan
  [26.9124, 75.7873], [24.5854, 73.7125], [26.2389, 73.0243],
  [25.1462, 75.8268], [28.0229, 73.3119], [27.5530, 76.6346],
  // Punjab & Haryana
  [30.7333, 76.7794], [31.1471, 75.3412], [31.6340, 74.8723],
  [29.0588, 76.0856], [29.9695, 76.9797],
  // Himachal Pradesh & Uttarakhand
  [31.1048, 77.1734], [32.2432, 76.3234], [30.3165, 78.0322],
  [29.3919, 79.4542],
  // Jammu & Kashmir
  [32.7266, 74.8570], [34.0837, 74.7973],
  // Madhya Pradesh
  [23.2599, 77.4126], [22.7196, 75.8577], [23.8388, 78.7378],
  [24.1097, 76.5816], [22.0344, 79.2961],
  // Chhattisgarh
  [21.2514, 81.6296], [22.0574, 82.1391], [20.4625, 81.8752],
  // Jharkhand
  [23.3441, 85.3096], [22.8046, 86.2029], [23.6693, 86.1511],
  // West Bengal (inland)
  [22.5726, 88.3639], [23.2324, 87.0753], [24.0961, 88.2636],
  [26.7271, 88.3953],
  // Odisha (inland)
  [20.2961, 85.8245], [21.4669, 83.9756], [20.4626, 84.6763],
  // Maharashtra (inland)
  [18.5204, 73.8567], [21.1458, 79.0882], [19.9975, 73.7898],
  [20.5519, 74.9558], [17.6599, 75.9064],
  // Gujarat (inland)
  [23.0225, 72.5714], [22.3072, 73.1812], [22.7197, 71.1916],
  [23.2156, 72.6369],
  // Telangana & Andhra Pradesh (inland)
  [17.3850, 78.4867], [18.1124, 79.0193], [15.8281, 78.0373],
  [16.3067, 80.4365], [14.9091, 78.0136],
  // Karnataka (inland)
  [12.9716, 77.5946], [12.2958, 76.6394], [15.3173, 75.7139],
  [14.4426, 75.9100], [15.0036, 76.7794],
  // Tamil Nadu (inland)
  [11.6643, 78.1460], [11.0168, 76.9558], [10.7905, 78.7047],
  [9.9252,  78.1198],
  // Kerala (inland)
  [10.5276, 76.2144], [11.0730, 76.0740], [10.0004, 76.9408],
  // North-East
  [26.1445, 91.7362], [26.7509, 94.2037], [24.8170, 93.9368],
  [25.6751, 94.1086], [27.5330, 88.5122], [23.9408, 91.9882],
];

// ±0.15° ≈ ±17 km — small enough to stay on land for all anchor points above
const COORD_JITTER = 0.15;

const ALERT_TYPES = ['TRAFFIC', 'CLIMATE', 'CLOSURE', 'ACCIDENT'];

const DESCRIPTIONS = {
  TRAFFIC: [
    'Heavy congestion on major arterial road due to peak-hour rush',
    'Multi-vehicle pile-up on expressway causing major delays',
    'Waterlogging on arterial roads slowing traffic to a crawl',
    'Accident-triggered bottleneck near flyover causing 3 km tailback',
    'Construction work on main road reducing carriageway to single lane',
    'Oversized load convoy causing slow movement on national highway',
    'Signal failure at major intersection leading to gridlock',
    'Truck breakdown blocking left lane of expressway near toll plaza',
    'Rush-hour congestion at busy urban junction; delays of 40 minutes',
    'Road narrowing due to utility works causing heavy build-up',
    'Stalled vehicle on main carriageway blocking two lanes',
    'Protest march diverting traffic off primary road corridor',
    'Unregulated parking near market area reducing road capacity',
    'School zone congestion during drop-off hours causing spillback',
    'Fuel tanker moving at low speed causing queue on bypass road',
    'Heavy goods vehicle convoy restricting overtaking on highway',
    'Temporary traffic light installation causing unexpected delays',
    'Pothole repair work blocking one lane during peak hours',
    'Slow-moving tractor on main road backing up highway traffic',
    'Ambulance corridor clearing causing brief stoppage on expressway',
    'Unmarked speed breaker causing sudden braking and rear-end queues',
    'Vehicles merging from feeder road creating bottleneck on bypass',
    'Diversion due to ongoing event causing congestion on alternate route',
    'Traffic backing up past interchange due to downstream blockage',
    'Long-haul trucks queuing at weigh station spilling onto main road',
    'Dust and reduced visibility from nearby site slowing traffic',
    'Cattle on road causing sudden stops and tailback on rural highway',
    'Flash mob activity blocking intersection; police managing flow',
    'Broken-down bus blocking bus bay and merging lane',
    'Overnight road works extended into morning peak causing delays',
  ],
  CLIMATE: [
    'Red alert issued for heavy rainfall and thunderstorms in the region',
    'Dense fog advisory: visibility below 50 m on roads',
    'Cyclone warning: strong winds and rough seas expected along coast',
    'Heatwave alert: temperature forecast to touch 46°C in the afternoon',
    'Flash flood warning following continuous overnight rainfall',
    'Cold wave alert: temperature expected to drop to near-freezing',
    'Dust storm advisory: strong dry winds reducing visibility',
    'Orange alert for extremely heavy rainfall over next 24 hours',
    'Severe thunderstorm warning with risk of lightning strikes',
    'High wind advisory: gusts up to 80 km/h expected in open areas',
    'Hail storm forecast causing risk of vehicle and property damage',
    'Fog bank settling over low-lying roads; zero visibility patches reported',
    'Heavy snowfall warning for higher elevations; road icing likely',
    'Strong crosswind alert on elevated highway sections and bridges',
    'Coastal flooding advisory due to high tide combined with heavy rain',
    'Landslide risk elevated following 72 hours of continuous rainfall',
    'River flooding alert: water levels approaching danger mark',
    'Smog alert: air quality index in severe category; visibility reduced',
    'Yellow alert for isolated heavy spells; localised flooding possible',
    'Storm surge warning: low-lying coastal areas at risk of inundation',
    'Thunderstorm with heavy rain moving toward region; prepare for delays',
    'Temperature inversion causing ground-level fog across plains',
    'Heatwave conditions increasing road surface temperature; tyre blowout risk',
    'Severe cold snap with frost on road surfaces; skidding hazard',
    'Waterspout activity reported near coastline; mariners advised caution',
    'Moderate earthquake felt; road inspection teams deployed as precaution',
    'Strong monsoon currents expected to intensify over next 48 hours',
    'Loo (hot dry wind) advisory: outdoor exposure risky between noon and 4 PM',
    'Cyclonic circulation forming offshore; precautionary orange alert raised',
    'Unseasonal rainfall with thunder likely to disrupt transport networks',
  ],
  CLOSURE: [
    'Road section closed for full-depth resurfacing work',
    'Bridge undergoing structural repair; alternate route via bypass advised',
    'Mountain road closed due to landslide debris; clearance underway',
    'Road closed for annual maintenance until further notice',
    'Tunnel closed for safety inspection; expected reopening in 6 hours',
    'Section of expressway closed for carriageway strengthening; traffic diverted',
    'Flood-damaged road closed; engineers assessing structural integrity',
    'Road closed for public event; diversions in place until late evening',
    'Flyover ramp closed for bearing replacement; lane restriction in effect',
    'Rural road blocked by fallen tree following storm; clearance teams deployed',
    'Road closed due to gas pipeline burst; utility crew on site',
    'Overhead cable snapped across carriageway; road sealed until repair',
    'Bridge load limit imposed; heavy vehicles diverted to alternate crossing',
    'Expressway entry ramp closed for joint repair work; merge at next entry',
    'Road closure due to sewage line collapse beneath carriageway',
    'Section sealed off following discovery of unexploded ordnance nearby',
    'Road closed for culvert replacement; diversion via parallel route',
    'Slip road closed due to erosion of embankment; inspection ongoing',
    'Road blocked by rockfall; debris removal in progress',
    'Intersection closed for signal and road-marking upgrade work',
    'Temporary road closure for VIP movement; expected to reopen within 2 hours',
    'Service road closed for utility trench work; pedestrian diversion in place',
    'Road closed owing to chemical spill; hazmat team managing site',
    'Expressway closed between two interchanges for night-time concrete pour',
    'Rural track closed due to severe waterlogging; impassable for vehicles',
    'Underpass closed for waterproofing treatment; traffic using ground level',
    'Road closed near construction zone for crane lift operation',
    'Temporary closure for marathon event; road to reopen post finish line',
    'Road sealed after structural crack found in carriageway surface',
    'Bypass closed for widening works; single-lane operation on main road',
  ],
  ACCIDENT: [
    'Head-on collision between two trucks; one lane blocked',
    'Bus lost control on steep road; emergency services on site',
    'Car overturned on expressway; rescue operation in progress',
    'Tanker carrying fuel overturned; hazmat team deployed',
    'Motorcycle and heavy vehicle collision; ambulance dispatched',
    'Chain accident involving 5 vehicles; traffic moving on shoulder',
    'Vehicle struck road divider at high speed; debris on carriageway',
    'Tractor-trolley collision blocking rural road; police on scene',
    'Rear-end collision between two buses; passengers injured; lane closed',
    'Container truck jackknifed across two lanes; recovery vehicle en route',
    'Car skidded on wet surface and hit median barrier; one lane affected',
    'Three-vehicle collision at uncontrolled intersection; traffic diverted',
    'Goods vehicle rolled into ditch; road partially obstructed',
    'Cyclist hit by car near pedestrian crossing; emergency services arrived',
    'Passenger vehicle aquaplaned and struck barrier; tow truck requested',
    'Collision at toll plaza; vehicles backed up across multiple lanes',
    'Hit-and-run incident; police investigating; lane sealed as evidence',
    'Van lost tyre at speed causing multi-vehicle shunt; slow traffic',
    'Overloaded vehicle toppled near bridge approach; lane blocked',
    'Ambulance involved in road collision while on emergency call',
    'Vehicle fire following collision; fire brigade controlling blaze',
    'Pedestrian struck on road crossing; medical response team on site',
    'School bus involved in minor collision; passengers safe; road congested',
    'Car fell into roadside ditch due to poor visibility; rescue in progress',
    'Head-on collision in overtaking zone; serious injuries reported',
    'Gravel truck lost load on carriageway; debris spread across lanes',
    'Bike skidded on loose gravel; rider receiving first aid on site',
    'Two vehicles collided after brake failure at descent; road partially clear',
    'Collision at blind curve; one vehicle off-road; tow truck dispatched',
    'Minor fender-bender at busy junction causing secondary congestion',
  ],
};

const randomElement = (arr) => arr[Math.floor(Math.random() * arr.length)];

const jitter = () => (Math.random() * 2 - 1) * COORD_JITTER;

const buildRandomAlert = (alertType) => {
  const [baseLat, baseLng] = randomElement(INDIA_LAND_POINTS);
  return new Alert({
    latitude:    parseFloat((baseLat + jitter()).toFixed(8)),
    longitude:   parseFloat((baseLng + jitter()).toFixed(8)),
    alert_type:  alertType,
    description: randomElement(DESCRIPTIONS[alertType]),
  });
};

const seedAlerts = async () => {
  const batchSize = parseInt(process.env.SCHEDULER_BATCH_SIZE, 10) || 200;
  const perCategory = Math.floor(batchSize / ALERT_TYPES.length);

  const alerts = [];
  for (const type of ALERT_TYPES) {
    for (let i = 0; i < perCategory; i++) {
      alerts.push(buildRandomAlert(type));
    }
  }

  // Handle remainder entries (if batchSize is not divisible by 4)
  let remainder = batchSize - perCategory * ALERT_TYPES.length;
  let typeIndex = 0;
  while (remainder-- > 0) {
    alerts.push(buildRandomAlert(ALERT_TYPES[typeIndex++ % ALERT_TYPES.length]));
  }

  // Insert all alerts into MySQL, then publish each to Kafka
  const insertPromises = alerts.map(async (alert) => {
    const insertId = await alertRepository.createAlert(alert);
    alert.id = insertId;
    return alert;
  });

  const insertedAlerts = await Promise.all(insertPromises);
  console.log(`[Scheduler] Inserted ${insertedAlerts.length} alerts into DB at ${new Date().toISOString()}`);

  // Publish to Kafka — do not fail the scheduler if Kafka is down
  try {
    const publishPromises = insertedAlerts.map((alert) => kafkaProducer.publishAlert(alert));
    await Promise.all(publishPromises);
    console.log(`[Scheduler] Published ${insertedAlerts.length} alerts to Kafka topic="${process.env.KAFKA_TOPIC}"`);
  } catch (kafkaErr) {
    console.error('[Scheduler] Failed to publish alerts to Kafka (continuing):', kafkaErr.message);
  }
};

const start = () => {
  const intervalMinutes = parseInt(process.env.SCHEDULER_INTERVAL_MINUTES, 10) || 30;
  const cronExpression = `*/${intervalMinutes} * * * *`;

  // Seed immediately on startup
  seedAlerts().catch((err) => console.error('[Scheduler] Initial seed failed:', err));

  cron.schedule(cronExpression, () => {
    seedAlerts().catch((err) => console.error('[Scheduler] Scheduled seed failed:', err));
  });

  console.log(`[Scheduler] Started — seeding ${process.env.SCHEDULER_BATCH_SIZE || 200} alerts every ${intervalMinutes} minute(s)`);
};

module.exports = { start };
